// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIGSpWbO46aTqJPm8SsgwkHszNkw3Pbyk',
    appId: '1:1063920521751:web:55f1733e2df84421c88252',
    messagingSenderId: '1063920521751',
    projectId: 'fluttertodolist-6c342',
    authDomain: 'fluttertodolist-6c342.firebaseapp.com',
    databaseURL: 'https://fluttertodolist-6c342-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttertodolist-6c342.appspot.com',
    measurementId: 'G-Z5PZWFRLLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxe_8oPSi8jTICtlo7e1W40vZv-gd73-w',
    appId: '1:1063920521751:android:67458404ab3f9b46c88252',
    messagingSenderId: '1063920521751',
    projectId: 'fluttertodolist-6c342',
    databaseURL: 'https://fluttertodolist-6c342-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttertodolist-6c342.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwJJSEU-ALgVjGTEIPiOx00UhFw8mRq4E',
    appId: '1:1063920521751:ios:ff0f4c9d9afa36afc88252',
    messagingSenderId: '1063920521751',
    projectId: 'fluttertodolist-6c342',
    databaseURL: 'https://fluttertodolist-6c342-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttertodolist-6c342.appspot.com',
    iosClientId: '1063920521751-2aij6700m8ld6ot6sqkgkraprsrel7sn.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwJJSEU-ALgVjGTEIPiOx00UhFw8mRq4E',
    appId: '1:1063920521751:ios:ff0f4c9d9afa36afc88252',
    messagingSenderId: '1063920521751',
    projectId: 'fluttertodolist-6c342',
    databaseURL: 'https://fluttertodolist-6c342-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttertodolist-6c342.appspot.com',
    iosClientId: '1063920521751-2aij6700m8ld6ot6sqkgkraprsrel7sn.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1',
  );
}
